### PR TITLE
Add support for `TextInput` decorations

### PR DESCRIPTION
**Pull request by GerardasB**
This PR adds support for `TextInput` decorations, i.e. start icon, end icon, prefix and suffix is now supported by `TextInput` by using the compositional approach.

Consumers can now render `TextInput` in two ways:

```tsx
// A standalone `input` element
<TextInput.Input defaultValue="Hello" />

// Using a wrapper element to display decorations:
<TextInput.Root>
  <TextInput.Input defaultValue="Hello" />
  <TextInput.Icon href={...} />
</TextInput.Root>
```

Builds on https://github.com/iTwin/kiwi/pull/99

`TextInput` will be renamed to `TextBox` in a separate PR: https://github.com/iTwin/kiwi/pull/130

### CODE REVIEW

**Review by RichardHill — APPROVED** [review]
GTG

**Review by knowler — DISMISSED** [review]
I might make a PR with some of the changes I’m suggesting here as they’re a bit complicated.

**Review by mayank99 — APPROVED** [review]
LGTM ⌨️

The remaining comments I've left are pretty minor.

**Review by knowler — APPROVED** [review]
Looking good to me. Thanks for all of your hard work on this, @GerardasB.

**Pull request merged**
